version: "3.4"

networks:
  banco:
  web:
  fila:

services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    container_name: "containerBancoDeDados"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - .docker/data/db:/var/lib/mysql
    networks: 
      - banco

  frontend:
    image: nginx:1.13
    container_name: "containerFrontEnd"
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app

  app:
    image: python:3.6
    container_name: "containerApp"
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - web
      - banco
      - fila
    depends_on: 
      - db
      - filaService

  filaService:
    image: redis:3.2
    container_name: "containerFila"
    networks:
      - fila

  worker:
    image: python:3.6
    container_name: "containerWorker"
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - filaService